services:
  - type: web
    name: rangoon-middleware
    env: python
    plan: standard
    region: singapore
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 30
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/uploads
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      
      # Security & Authentication
      - key: SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_MINUTES
        value: 30
      
      # Database
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      
      # ERP Integration
      - key: ERP_BASE_URL
        sync: false
      - key: ERP_API_KEY
        sync: false
      - key: ERP_API_SECRET
        sync: false
      - key: ERP_COMPANY
        value: Myanmar ShweTech
      - key: ERP_TIMEOUT
        value: 30
      - key: ERP_MAX_RETRIES
        value: 3
      
      # File Processing
      - key: MAX_FILE_SIZE_MB
        value: 50
      - key: ALLOWED_FILE_TYPES
        value: "xlsx,xls,csv"
      - key: UPLOAD_DIR
        value: /opt/render/uploads
      
      # CORS
      - key: CORS_ORIGINS
        value: "http://localhost:3000,https://your-frontend-domain.com"

  # Redis Service for Caching & Sessions
  - type: redis
    name: rangoon-redis
    plan: free
    region: singapore
    maxmemoryPolicy: allkeys-lru

# Environment Groups for shared variables
envVarGroups:
  - name: security-config
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ERP_API_KEY
        sync: false
      - key: ERP_API_SECRET
        sync: false
  
  - name: external-services
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: ERP_BASE_URL
        sync: false
