services:
  - type: web
    name: rangoon-middleware
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ERP_BASE_URL
        sync: false
      - key: ERP_API_KEY
        sync: false
