services:
  - type: web
    name: rangoon-middleware
    env: python
    plan: standard
    region: singapore
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: ENVIRONMENT
        value: production
      
      # Your ERP Keys
      - key: ERP_API_KEY
        sync: false
      - key: ERP_API_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
